companymodels/urls.py
from django.urls import path
from . import views


app_name = 'company'
urlpatterns = [
    path('', views.homePage, name='login'),
    path('userpage/', views.userPage, name='userpage'),
    path('newuser/', views.newUser, name='newuser'),
    path('neworder/', views.newOrder, name='neworder'),
    path('newservice/', views.newService, name='newservice'),
    path('logout/', views.logout, name='logout'),
    path('newticket/', views.newTicket, name='newticket'),
    path('ticket/', views.ticketReview, name='ticketreview')
]

models/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/', include('companymodels.urls'))
]

companymodels/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    def __str__(self):
        return self.user.username


class ContactInfo(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name='contactinfo')
    email = models.EmailField(max_length=20)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=2000, null=True, blank=True)

    def __str__(self):
        return self.user.user.username + "::" + self.email + "::" + self.phone


class Service(models.Model):
    serviceName = models.CharField(max_length=30)
    fee = models.PositiveIntegerField()

    def __str__(self):
        return self.serviceName + "::" + str(self.fee)


class Invoice(models.Model):
    totalCost = models.PositiveIntegerField(blank=True, null=True)
    paid = models.PositiveIntegerField(blank=True, null=True)
    debt = models.PositiveIntegerField(blank=True, null=True)

    def calculateTotalCost(self):
        self.totalCost = self.order.cost

    def calculateDebt(self):
        self.debt = int(self.totalCost) - int(self.paid)

    def __str__(self):
        return 'Total Cost : ' + str(self.totalCost) + ' To Pay : ' + str(self.debt)


class Order(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='orders')
    factor = models.OneToOneField(Invoice, on_delete=models.CASCADE, related_name='order', blank=True, null=True)
    cost = models.PositiveIntegerField(blank=True, null=True)
    services = models.ManyToManyField(Service, related_name='orders', blank=True, null=True)

    def calculateCost(self):
        self.cost = 0
        for s in self.services.all():
            self.cost += s.fee

    def __str__(self):
        string = str(self.user) + '\n'
        for service in self.services.all():
            string += str(service)
            string += '\n'
        return string


class Ticket(models.Model):
    choices = [(1, 'responded'),
               (2, 'notResponded')]
    status = models.CharField(choices=choices, max_length=32)
    title = models.TextField()
    creator = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='tickets')

    def __str__(self):
        return self.title + " :: Status : " + self.status


class Message(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='messages')
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='messages')
    body = models.TextField()

    def __str__(self):
        return self.author + "::" + self.body

companymodels/views.py
from django.shortcuts import render, redirect
from . import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout as django_logout
from django.contrib import messages


def createNewUser(username, password, email, phoneNumber):
    user = models.User.objects.create_user(username, password=password)
    profile = models.Profile.objects.create(user=user)
    models.ContactInfo.objects.create(user=profile, email=email, phone=phoneNumber)
    return user


def createNewService(form, request):
    user = request.user.profile
    form = models.Service.objects.create(serviceName=form['name'], fee=form['fee'], user=user)


def createNewOrder(form, user):
    order = models.Order.objects.create(user=user.profile)
    for service in models.Service.objects.all():
        if form.get(service.serviceName) == 'on':
            print("bos")
            order.services.add(service)
    order.calculateCost()
    invoice = models.Invoice.objects.create(paid=0)
    order.factor = invoice
    invoice.calculateTotalCost()
    invoice.calculateDebt()
    invoice.save()
    order.save()


def createNewTicket(form, user):
    ticket = models.Ticket.objects.create(title=form['title'], creator=user, status=1)
    models.Message.objects.create(ticket=ticket, author=user, body=form['body'])


def homePage(request):
    if request.user.is_authenticated:
        return redirect('company:userpage')
    if request.method == 'POST':
        form = request.POST
        user = authenticate(request,  password=form['password'], username=form['username'])
        if user is not None:
            login(request, user)
            messages.success(request, 'You Logged in successfully!')
            return redirect("company:userpage")
        else:
            messages.error(request, 'Wrong Username or Password')
            return redirect('company:login')
    return render(request, 'companymodels/homepage.html')


def newUser(request):
    if request.user.is_authenticated:
        messages.warning(request, 'Log out first')
        return redirect('company:userpage')
    if request.method == 'POST':
        form = request.POST
        try:
            user = createNewUser(form['username'], form['password'], form['email'], form['phone'])
            user = authenticate(request, username=form['username'], password=form['password'])
            login(request, user)
            messages.success(request, 'Your account created successfully and you\'re logged in!')
            return redirect('company:userpage')
        except Exception:
            messages.error(request, 'Can\'t make your account!')
    return render(request, 'companymodels/newuser.html')


@login_required()
def userPage(request):
    user = request.user.profile
    if request.method == 'POST':
        orderID = request.POST['orderID']
        models.Order.objects.get(id = orderID).delete()
    orders = user.orders.all()
    service = models.Service.objects.all()
    tickets = user.tickets.all()
    allTickets = models.Ticket.objects.all()
    context = {'orders': orders, 'services': service, 'tickets': tickets, 'allTickets': allTickets}
    return render(request, 'companymodels/userpage.html', context)


@login_required()
def logout(request):
    django_logout(request)
    messages.success(request, 'You logged out successfully!')
    return redirect('company:login')


@login_required()
def newOrder(request):
    user = request.user
    if request.method == 'POST':
        form = request.POST
        createNewOrder(form, user)
        messages.success(request, 'You order added successfully!')
        return redirect('company:userpage')
    context = {'services': models.Service.objects.all()}
    return render(request, 'companymodels/neworder.html', context)


@login_required()
def newService(request):
    if not request.user.is_superuser:
        messages.warning(request, 'Access Denied')
        return redirect('company:userpage')
    if request.method == 'POST':
        form = request.POST
        try:
            createNewService(form, request)
            messages.success(request, 'You\'re service added succssfully!')
            return redirect('company:userpage')
        except Exception:
            messages.error(request, 'Could\'nt add the service')
    return render(request, 'companymodels/newservice.html')


@login_required()
def newTicket(request):
    if request.method == 'POST':
        form = request.POST
        user = request.user.profile
        try:
            createNewTicket(form, user)
            messages.success(request, 'Your Ticket successfully sent!')
            return redirect('company:userpage')
        except Exception:
            messages.error(request, 'Can\'t make your ticket!')
    return render(request, 'companymodels/newticket.html')


@login_required()
def ticketReview(request):
    user = request.user
    if user.is_superuser:
        tickets = models.Ticket.objects.all()
    else:
        tickets = user.profile.tickets.all()
    context = {'tickets': tickets}
    return render(request, "companymodels/ticketreview.html", context)

companymodels/templates/companymodels/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
</head>
<body>
    {{ database.User }}
    <form action=""  method='POST'>
        {% csrf_token %}
        Username : <input type="text" name="username", required>
        Password : <input type="password" name="password", required>
        <input type="submit" value="submit">
    </form>
    {% if messages  %}
        {% for m in messages %}
            {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <p class="error"> {{ m }} </p>
            {% elif m.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <p class="success"> {{ m }} </p>
            {% else %}
                <p> {{ m }} </p>
            {% endif %}
        {% endfor %}
    {% endif %}
    <br>
    <a href="{% url 'company:newuser' %}">Create an Account</a>
</body>
</html>

companymodels/templates/companymodels/neworder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Order</title>
</head>
<body>
    <form action="" method="post">
    {% csrf_token %}
        <label>Choose your desierd services : </label>
        {% for service in services %}
            <input type="checkbox" id='{{ service.serviceName }}', name="{{ service.serviceName }}">
            <label for="{{ service.serviceName }}">{{ service }}</label>
        {% endfor %}
        <input type="submit" value="submit">
    </form>


</body>
</html>

companymodels/templates/companymodels/newservice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Service</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        Service Name: <input type="text" name="name" required>
        Fee : <input type="number", name="fee" required>
        <input type="submit" value="submit">
    </form>
    {% for m in messages %}
        <p>{{ m }}</p>
    {% endfor %}
</body>
</html>

companymodels/templates/companymodels/newticket.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Ticket</title>
</head>
<body>
    <form action="" method="post">
        Ticket Title : <input type="text" name="title" required>
        Ticket Body : <input type="text" name="body" required>
        <input type="submit" value="submit">
    </form>
    {% if messages  %}
        {% for m in messages %}
            {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <p class="error"> {{ m }} </p>
            {% elif m.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <p class="success"> {{ m }} </p>
            {% else %}
                <p> {{ m }} </p>
            {% endif %}
        {% endfor %}
    {% endif %}
</body>
</html>

companymodels/templates/companymodels/newuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <link rel="stylesheet" type="text/css" href="{% static 'simpleview/style.css' %}">#}
    <title>Sign Up</title>
</head>
<body>
    <form method="post" action=''>
        {% csrf_token %}
        Username : <input type="text" name="username", required>
        Password : <input type="password" name="password", requirede>
        Email : <input type="email" name="email", required>
        Phone number : <input type="text" name="phone", required>
        <input type="submit" value="submit">
    </form>
    {% if messages  %}
        {% for m in messages %}
            {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <p class="error"> {{ m }} </p>
            {% elif m.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <p class="success"> {{ m }} </p>
            {% else %}
                <p> {{ m }} </p>
            {% endif %}
        {% endfor %}
    {% endif %}
</body>
</html>

companymodels/templates/companymodels/ticketreview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ticket Review</title>
</head>
<body>
    {% for ticket in tickets %}
        <p>{{ ticket }}</p><br>
        {% for message in tickets.messages.all %}
            <p style="text-indent: 40px">{{ message }}</p><br>
        {% endfor %}
    {% endfor %}
    <form action="" method="post"></form>
</body>
</html>

companymodels/templates/companymodels/userpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <link rel="stylesheet" type="text/css" href="{% static 'simpleview/style.css' %}">#}
    <title>{{ request.user.username }}</title>
</head>
<body>
    <h2>welcom {{ request.user.username }}</h2>
    {% if messages  %}
        {% for m in messages %}
            {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <p class="error"> {{ m }} </p>
            {% elif m.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <p class="success"> {{ m }} </p>
            {% elif m.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                <p class="warning"> {{ m }} </p>
            {% else %}
                <p> {{ m }} </p>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if not request.user.is_superuser %}
        <h3>Orders Reviews</h3>
            {% if orders %}
                {% for order in orders %}
                    <h4>Invoice:{{ order.factor }}</h4>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="text" value="{{ order.id }}" name="orderID" hidden><input type="submit" value="delete">
                    </form>
                {% endfor %}
            {% else %}
                <h4>No order yet</h4>
            {% endif %}
            <br>
            <h3>Tickets Reviews</h3>
                {% if tickets %}
                    {% for ticket in tickets %}
                        <a href="{% url 'company:ticketreview' %}">{{ ticket }}</a>
                    {% endfor %}
                {% endif %}
    {% else %}
        <h3>Services Reviews</h3>
            {% if services %}
                {% for service in services %}
                    <h4>{{ service }}</h4>
                {% endfor %}
            {% else %}
                <h4>No service yet</h4>
            {% endif %}
        <br>
        <h3>Tickets Review</h3>
            {% for ticket in allTickets %}
                <a href="{% url 'company:ticketreview' %}"></a>
            {% endfor %}
    {% endif %}
    <br>
    {% if not request.user.is_superuser %}
        <a href={% url 'company:neworder' %}>Add New Order</a>
        <a href="{% url 'company:newticket' %}">Add new ticket</a>
   {% endif %}
    <br>
    {% if request.user.is_superuser %}
        <a href="{% url 'company:newservice' %}">New Service</a>
    {% endif %}
    <br>
    <a href={% url 'company:logout' %}>Log Out</a>
</body>
</html>